### ISSUE TITLE
Does the cloner also work for Akeneo 3.2 CE

### ISSUE THREAD

**Issue by TVO99** [flagbit/akeneo-product-cloner#20] opened 2019-12-07 17:50 UTC
Hi,

If the cloner works for version 3.0, does that mean it will also work for subreleases like 3.2.22 ?
regards,
Tom

**Comment by vasik-bukhari** [comment] 2019-12-10 06:44
I have tried with akeneo 3.2.3 and it is not getting installed getting the following dependency issues after running the command "composer require flagbit/product-cloner-bundle"

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - akeneo/pim-community-dev v3.2.3 requires php 7.2.* -> your PHP version (7.3.8) does not satisfy that requirement.
    - akeneo/pim-community-dev v3.2.3 requires php 7.2.* -> your PHP version (7.3.8) does not satisfy that requirement.
    - akeneo/pim-community-dev v3.2.3 requires php 7.2.* -> your PHP version (7.3.8) does not satisfy that requirement.
    - Installation request for akeneo/pim-community-dev (locked at v3.2.3, required as ~3.2.3) -> satisfiable by akeneo/pim-community-dev[v3.2.3].

Installation failed, reverting ./composer.json to its original content.

You can also check the below image.

![image](https://user-images.githubusercontent.com/57760809/70502324-78688d80-1b46-11ea-8955-e304e2bfba12.png)

**Comment by TVO99** [comment] 2019-12-10 15:26
Hi,
I have tested this also, and came to the same conclusion. I notice from your screenshot that you are, just as me, using the bitnami akeneo package.

They (the bitnami akeneo team) have just coonfirmed to me that they packaged the wrong perl version for akeneo (7.3 instead of 7.2):

https://community.bitnami.com/t/install-plugin-flagbit-product-cloner-on-akeneo-3-2-16-0-fails-with-wrong-perl-version/72158

So unless we find a workaround to this, all we can do is wait until bitnami releases a new akeneo release with the correct perl version I'm afraid.

regards,
Tom

**Comment by amansilla** [comment] 2019-12-12 08:41
Hi @TVO99 and @vasik-bukhari!

First thank you for submitting the issue but I guess in this case the issue is not related to this extension. As I can see you both are using a bitnami and from the output you posted I can see that you've the wrong PHP language version installed in your server, that's in fact the issue. So the right way to go ahead would be contact your hoster and say the should install PHP `7.2` instead `7.3`. After this is fixed, you should be able to install the extension.

I'll close the issue since it's no related with this Akeneo extension.

**Closed by amansilla** 2019-12-12 08:41 UTC
